//LOADING
export const LOADING='LOADING'
export const GETALLPRODUCTSSUCCESS='GETALLPRODUCTSSUCCESS'
 export const  PRODUCTFAILED='PRODUCTFAILED'

 //Add product
export const ADDPRODUCTSUCCESS  ='ADDPRODUCTSUCCESS'
// delete product
export const DELETEPRODUCTSUCCESS='DELETEPRODUCTSUCCESS'
//ProductDetailes
export const GETONEPRODUCTSUCCESS ='GETONEPRODUCTSUCCESS'
//edit product
export const EDITPRODUCTSUCCESS='EDITPRODUCTSUCCESS'